### ISSUE TITLE
Regex not working?

### ISSUE THREAD

**Issue by Fuchsium** [rangoo94/universal-lexer#1]
Hello, I am using this lexer for my language. For some reason, the lexer fails to match my regex with my command, even though I have tested it with [Regexr](regexr.com).

Here is my JSON:
```JSON
[
 {
   "type" : "FuncCall",

   "valid" : "\\do",

   "regex" : "do (?<value>[^\\d][\\d\\D]+)",
   "regexFlags" : "i"
  }
]
```
Here is my js:
```javascript
const UniversalLexer = require('universal-lexer/browser');

const fs = require('fs');
const object = JSON.parse(fs.readFileSync('dictonary.json', 'utf8'));
console.log(obj);

const lexer = UniversalLexer.compile(obj);
const tokens = lexer('do yes');
if(tokens.error!===undefined) {
    console.error("Error: "+tokens.error);
} else {
    console.log(tokens.tokens);
}
```
This is the console result:
```
[ { type: 'FuncCall',
    valid: '\\do',
    regex: 'do (?<value>[^\\d][\\d\\D]+)',
    regexFlags: 'i' } ]
Error: Unrecognized token
```

**Comment by rangoo94** [comment]
Hello @AteurGames, thanks for the message :)

I executed your code and it has some slight issues, so I modified it a little. The code which I was using:

```js
const UniversalLexer = require('universal-lexer/browser');

const fs = require('fs');
const object = JSON.parse(fs.readFileSync('dictonary.json', 'utf8'));
console.log(object);

const lexer = UniversalLexer.compile(object);
const tokens = lexer('do yes');

if (tokens.error!===undefined) {
    console.error("Error: "+tokens.error);
} else {
    console.log(tokens.tokens);
}
```

The "Unrecognized token" error here, is because nothing can match `FuncCall` rule - `valid` will not match `regex` (with `\` on the beginning). There are two options to resolve your problem:

* Remove `valid` (which is used mostly for optimizations, with simpler expression)
* Use `do` or `do ` in `valid` option

```json
[
 {
   "type" : "FuncCall",

   "valid" : "do ",

   "regex" : "do (?<value>[^\\d][\\d\\D]+)",
   "regexFlags" : "i"
  }
]
```

Based on this definition, I get `[ { type: 'FuncCall', data: { value: 'yes' }, start: 0, end: 6 } ]` result.

I hope that it helps!

**Comment by Fuchsium** [comment]
Thank you! I will mark this as closed.
